### ISSUE TITLE
Beim Herauszoomen werden die Linien zu dick angezeigt

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#117]
![grafik](https://user-images.githubusercontent.com/474596/68590887-d8a8d880-048f-11ea-96bf-a73e972a5538.png)
vgl. https://fixmyberlin.de/zustand

**Comment by chrtze** [comment]
Konnte über Mapbox Studio gefixt werden. Lag daran, dass die side-1 und side-0 layer nicht ausgeblendet wurden.
