### ISSUE TITLE
Herausgezoomt bekomme ich keine Infobox beim Onclick

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#118]
https://fixmyberlin.de/zustand
![grafik](https://user-images.githubusercontent.com/474596/68591106-3fc68d00-0490-11ea-8cc2-011c05b05f29.png)

**Comment by chrtze** [comment]
Konnte über mapbox Studio gefixt werden. Lag daran, dass die Klick-Fläche beim rauszoomen ausgeblendet wurde.
![Screenshot 2019-11-14 at 16 28 55](https://user-images.githubusercontent.com/3797215/68871099-36415d00-06fc-11ea-92fb-ca6486d3a7e1.png)
