### ISSUE TITLE
Als Besucher:in möchte ich Planungen auch als PDF exportieren können

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#12]
- Bei Planungs-Ansichten (Planungen, Meldungen von Radbügeln) soll es einen druckfähigen und e-mail-versandfähigen PDF Export geben
- Layout: LINK zur PDF-Vorlage

**Comment by ciex** [comment]
Soll dies umgesetztr werden?

**Comment by Hejco** [comment]
Ja soll umgesetzt werden, ich kann im Januar das Layout dafür machen.

**Comment by ciex** [comment]
@Hejco ich hab dir dafür mal eine Karte ans Board im Büro geschrieben

**Comment by ciex** [comment]
Dieses Ticket wird vorerst geschlossen, bis wir User Research über die Anforderungen an den Ausdruck durchgeführt haben.
