### ISSUE TITLE
Kreuzungen sehen fehlerhaft aus

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#120]
Staging:
https://release--fixmyberlin-staging.netlify.com/zustand/512/
![grafik](https://user-images.githubusercontent.com/474596/68592086-8f0dbd00-0492-11ea-812e-b5fcffc6a701.png)

Live:
![grafik](https://user-images.githubusercontent.com/474596/68593091-f167bd00-0494-11ea-9c94-6b6072c30419.png)

**Comment by chrtze** [comment]
Overlay wurde nicht angezeigt, da sich die Bezeichnung in Mapbox geändert hat.
