### ISSUE TITLE
Abschließende Anpassungen Design / Layout

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#130]
- [x] mobile sind die Untertitelungen der Bewertungsbuttons verrutscht.
![IMAGE 2019-11-21 16:53:07](https://user-images.githubusercontent.com/39826825/69353827-65694880-0c7f-11ea-8547-7cc5df800f01.jpg)

- [x] Abstand zwischen Szenenbildern und Frage soll größer sein  (s.Layout) 
<img width="685" alt="Screenshot 2019-11-21 16 41 14" src="https://user-images.githubusercontent.com/39826825/69352769-c132d200-0c7d-11ea-93ef-60cfc7f38904.png">

- [x] Auf Desktop sollen alle Buttons einheitlich 500 px breit sein  (sind derzeit 400 oder 500)

- [x] Der Feedback Screen soll in den einheitlichen Breiten gestyled sein. Layout dazu: https://zpl.io/VqkBAL5
- [x] padding Buttons bitte schmaller auf 14 statt 16 ;)

**Comment by ciex** [comment]
Beim Review ist ein Missverständnis aufgefallen: Die Buttons, deren padding du geändert hattest @moklick sollen eigentlich padding 16px behalten - statdessen soll die margin-bottom auf 26px sein. 

Außerdem wünscht sich Heiko, dass dass es zwischen rating-fragetext und rating-buttonreihe einen abstand von 25px gibt. 

Das Ladebild hat ein anderes Seitenverhältnis als die Szenenbilder, dazu schickt dir Heiko noch eine neue Version.

**Comment by Hejco** [comment]
habe die margin-Änderungen bereits eingepflegt: https://deploy-preview-233--fixmyberlin-staging.netlify.com/strassencheck/szenen/2
