### ISSUE TITLE
Nach drücken der Buttons bekomme ich eine Feedbackanimation

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.platform#144]
Statt der derzeitigen Ladeanimation sollen die Bewertungsbuttons und die Auswahlbuttons der Fragen eine Feedbackanimation bekommen.
zur Orientierung: <img width="480" alt="Screenshot 2019-11-22 17 46 10" src="https://user-images.githubusercontent.com/39826825/69444221-353daa80-0d50-11ea-85fc-02f67e0e99d0.png">

**Comment by ciex** [comment]
Fixes https://github.com/FixMyBerlin/fixmy.platform/issues/188

**Comment by moklick** [comment]
I used the existing like animation for this effect.
