### ISSUE TITLE
Antwort-Option bereits vorausgewählt

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#149]
Wenn ich beispielsweise bei der ersten Frage "Baustellen auf der Fahrbahn" auswähle, ist beim zweiten Screen "Ja, häufig" bereits vorausgewählt.
Gehe ich zurück und wähle die zweite Antwort, ist auf dem zweiten Screen auch die zweite Antwort ausgewählt, etc.
Auf einem Android, FF, Huawei p9 plus

**Comment by ciex** [comment]
Kannst du das auf staging nochmal testen und ggf. vorher deinen browser cache leeren? Meine Browser zeigen diesen Rahmen nicht, aber ich glaube er ist jetzt weg.
