### ISSUE TITLE
Bei Korrekturen wird die falsche Auswahl immer noch angezeigt

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#150]
Ich hatte fälschlicherweise "18-24" ausgewählt, bin zurück und habe "unter 18" ausgewählt. Die Option "18-24" bleibt auf dem Screen ausgewählt, sollte aber jedoch desektiert werden
![grafik](https://user-images.githubusercontent.com/474596/69497895-140cc380-0ee2-11ea-97c9-0607cde84b88.png)

**Comment by ciex** [comment]
Sollte durch https://github.com/FixMyBerlin/fixmy.frontend/pull/234 gelöst sein
