### ISSUE TITLE
Fehlermeldung zu Nutzerprofil irreführend

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#153]
![grafik](https://user-images.githubusercontent.com/474596/69498153-e1b09580-0ee4-11ea-98fd-633ca6f97f2b.png)
Wir speichern kein Nutzerprofil.

Besser: "Ups, da ist etwas schiefgegangen: Ihre Antworten konnte nicht übertragen werden."

Ergänzung dann noch: "Bitte kontrollieren Sie Ihre Internet-Verbindung."

**Comment by ciex** [comment]
https://github.com/FixMyBerlin/fixmy.platform/issues/155
