### ISSUE TITLE
Neu erstellter User mit newsletter=true landet nicht in Mailjet

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#16]

**Comment by cafca** [comment]
@hekele mir ist nicht ganz klar, was hier gemeint ist. Ist das noch aktuell und wenn ja, kannst du nochmal sagen worum es geht?

**Comment by ohrie** [comment]
Ich habe die Newsletteranmeldung auf der Startseite getestet und diese funktioniert. Ich betrachte diesen Issue als geschlossen.
