### ISSUE TITLE
Startseite von fixmyberlin.de soll auf die Umfrage verlinken

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.platform#161]
Die Startseite unter fixmyberlin.de soll aktualisiert werden und auf die Umfrage verlinken: Layout: https://zpl.io/bLn4Q1D (ähnlich, wie beim Meldedialog)

**Comment by ciex** [comment]
Link auf Standalone-Version: https://interaktiv.tagesspiegel.de/strassencheck/
