### ISSUE TITLE
Einleitender Text für Sharing-Buttons

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#173]
Es fehlen die Sharing-Buttons für Desktop

**Comment by moklick** [comment]
Sharing Buttons werden angezeigt wenn natives Sharing unterstützt wird. Auf Desktop ist das nur Safari.

**Comment by ciex** [comment]
Auf Desktop gibt es auch Sharing-Buttons auf der Feedback-Seite. In welcher Situation werden die nicht gezeigt @d-m- ?

![image](https://user-images.githubusercontent.com/278463/69649235-06377980-106d-11ea-8faf-cd51865e0f6c.png)

**Comment by d-m-** [comment]
Ups, sorry, das hatte ich mir notiert als es die noch nicht gab. Vorschlag von uns: 
Über die Buttons einen kurzen Text ("Umfrage teilen", vielleicht sogar was längeres "Danke fürs Mitmachen, würden uns freuen wenn Sie die Umfrage teilen",...). So ist nicht hundert Prozent klar was man teilt (die Umfrage? Dass es schon X Bewertungen gibt? Dass ich mitgemacht habe?). Die Buttons könnten dann auch kompakter werden (ohne "Auf" und "teilen").

**Comment by ciex** [comment]
ok, dann brauchen wir noch einen text von @Hejco

**Comment by Hejco** [comment]
Habe das Layout aktualisiert, bitte entsprechend umsetzen. https://zpl.io/VqkBAL5
