### ISSUE TITLE
Unnötiger screen bei freiwilligem weiterbewerten

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#174]
Wenn ich mich entschloßen habe noch weitere 5 Renderings aus Perspektive X zu bewerten brauche ich nicht nochmal den Screen "Wir zeigen ihnen nun 5 Szene aus Perspektive X"

**Comment by ciex** [comment]
Klingt vernünftig

**Comment by Hejco** [comment]
Ja sehe ich auch so, hat aber eher niedrigere Priorität @ciex
