### ISSUE TITLE
Gesamthöhe des UI, vor allem bei den Renderings

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#176]
Bin mir nicht sicher wie sich das lösen lässt, aber: Auf kleinen Laptops ist die Umfrage, vor allem das Bewerten der Renderings etwas unbequem, weil man die ganze zeit scrollen muss. Beispiel: MacBook 13" hat, wegen Browser-Bars, Menü-Leiste etc noch eine Höhe von ca. 650 Pixeln. In so einem Fall sind die Buttons abgeschnitten und man muss scrollen.

Um das Problem etwas abzumildern habe ich für Viewports mit ausreichender Breite die "Umfrage schließen"-Leiste durch einen Button ersetzt, was schonmal 40px spart.

**Comment by ciex** [comment]
So sieht es mit 800x650 aus.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/278463/69714485-c2914e00-1106-11ea-895d-34a440865b58.png">

**Comment by Hejco** [comment]
Der Screen müsste responsive sein in der Form, dass Bild und Fragetext ja nach Höhe mitskalieren. --> Breite verringert sich, Fontsize wechselt bei Browserwindowhöhe unter XX auf die Mobileversion (26 pt), ggf. auch noch die Margins dynamisch machen.  Habe das hier für eine 700er Höhe als Layout angelegt: https://zpl.io/VkzrzXG

**Comment by Hejco** [comment]
new issue #196
