### ISSUE TITLE
Beschriftung Slider

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#178]
Nur als Hinweis: Schade dass die beschriftungen oben weg sind, jetzt muss man alle Positionen ausprobieren, um zu sehen was sie bedeuten.

**Comment by ciex** [comment]
Ich sehe bei Hover und während des Verschiebens Beschriftungen überhalb der Slider? Auf welchem Gerät und Browser beobachtest du das?

<img width="321" alt="image" src="https://user-images.githubusercontent.com/278463/69713268-89f07500-1104-11ea-81ed-45ff9ac5c471.png">

**Comment by d-m-** [comment]
Zwischendurch waren sie verschwunden. EIn Problem gibt es noch mit ihnen: In der maximalen Position ragen sie aus dem Viewport und führen zu horizontalem Scrollen.

**Comment by ciex** [comment]
Ok! In welchem Browser ist das gewesen?

**Comment by d-m-** [comment]
Firefox, Chrome.
