### ISSUE TITLE
Schriftgröße auf reinen Text-Slides mobil

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#181]
"Wir zeigen ihnen nun 5 Bilder aus Autoperspektive": Text hat zu große font-size: "Autoperspektive" ist breiter als der viewport bei 320px (und realistischerweise muss man auf kleinem Telefon scrollen, was bei der slide unnötig ist)

**Comment by ciex** [comment]
Fixed by https://github.com/FixMyBerlin/fixmy.frontend/pull/262
