### ISSUE TITLE
Textumbruch bei Checkboxen

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#182]
Auf kleinen Screen brechen die Labels so um, dass sie unter den Checkboxen liegen. Würde schöner aussehen wenn die Labels ein inline-block wären.

**Comment by ciex** [comment]
<img width="272" alt="image" src="https://user-images.githubusercontent.com/278463/69712788-b35cd100-1103-11ea-90fe-ac89ee39ba8d.png">
