### ISSUE TITLE
"Umfrage beenden"-Button

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#186]
Es sollte einen Button geben der einem explizit erlaubt die Umfrage zu Beenden (anstatt weitere Szenen zu bewerten). Standalone zu Dankeschön-Seite mit Sharing-Buttons und Link zum Tagesspiegel, embedded: postMessage

**Comment by ciex** [comment]
Der Button zum Beenden der Umfrage befindet sich auf dem Feedbackscreen

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/278463/69712209-bd320480-1102-11ea-948b-c9b86404718e.png">

Wenn ich den Button klicke wird mir eine Dankeschön-Seite gezeigt. Wenn diese auch noch Sharing-Buttons enthalten soll könntet ihr die dort auch einbauen. Die befinden sich allerdings auch auf dem Feedback-Screen.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/278463/69712264-d33fc500-1102-11ea-89f7-fa7d1835aa3e.png">

**Comment by d-m-** [comment]
Perfekt!
