### ISSUE TITLE
Anzahl der Schritte im Fortschrittsbalken

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#187]
Der Fortschrittsbalken oben ist manchmal unintuitiv: Vor allem wenn ich die zusätzlichen 5 Szenen mache ist er deutlich länger als erwartet. Auf der letzten Slide davon (wenn man schon durch ist) bleibt auch noch ein grauer Balken. Das ist etwas verwirrend.

**Comment by ciex** [comment]
Duplikat https://github.com/FixMyBerlin/fixmy.platform/issues/143
