### ISSUE TITLE
Farbe Fortschrittsbalken Umfragestand

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#192]
Wir haben von mehreren Leuten das Feedback bekommen, dass die Farbe des Fortschrittsbalken ("schon X von 1000 Bewertungen") eher negativ wirkt. Vorschläge waren das Gelb, oder Grau.

**Comment by ciex** [comment]
Wir brauchen dann eine genaue Farbe @Hejco

**Comment by Hejco** [comment]
Ist in #173 mit erfasst
