### ISSUE TITLE
Text zu Perspektivenwechsel

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#193]
bitte wie im verlinkten Layout umsetzen

„Sie können mit dieser Perspektive weiter machen“ versteht man nicht. Man braucht sowas wie „Sie haben Straßensituationen aus Fahrradperspektive bewertet. Sie können aus Sicht von anderen Verkehrsmitteln weitermachen:“

**Comment by Hejco** [comment]
Habe das Layout mit entsprechendem Text aktualisiert: https://zpl.io/259gBXo

**Comment by Hejco** [comment]
Fixes #212
