### ISSUE TITLE
Positionierung Logos Landing Page

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#194]
Vorschlag zu Positionierung der Logos (v.A. Desktop):
"Umfrage von" raus
FixMyBerlin Logo nach links.

**Comment by Hejco** [comment]
Habe es im Layout aktualisiert @d-m- bitte noch mal gucken. Auf Desktop fliegt es auseinander, wenn ich es links und mittig setze, daher beide links aus meiner Sicht am besten: https://zpl.io/2yEkYj9 https://zpl.io/V4oLxe8

**Comment by Hejco** [comment]
Hier bitte auch noch den Text zur Datenschutzerklärug sichtbarer machen, s. aktuelles Layout
