### ISSUE TITLE
Responsive UI Desktop

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.platform#196]
Bei der Desktopdarstellung sollte die Ansicht zur Bewertung der Szenen responsive sein, so dass möglichst immer Bild, Frage und Buttons ohne Scrollen zu sehen sind. Dafür sollen Bild und Fragetext ja nach Breite des Browserfensters mitskalieren. --> Die Breite der Spalte in der Bild uns Text liegen verringert sich, Fontsize wechselt nach eine bestimmten Browserbreiteauf die Mobileversion (26 pt), ggf. können auch noch die Margins dynamisch sein. Habe das hier beispielhaftals Layout angelegt: https://zpl.io/adwAZOl
Idealerweise sollte zusätzlich ein Breakpoint für größere Bildschirme definiert sein, der das bisherige Layout verwendet.

**Comment by Hejco** [comment]
fixes #176

**Comment by Hejco** [comment]
bitte die Schriftgröße auf 25 pt setzen, ist geschummelt, aber dann bleibt es einzeilig

**Comment by d-m-** [comment]
Kleine Anmerkung dazu: Die responsive Version ist cool, aber falls ihr noch Zeit dafür findet wäre es besser den break über max-height zu steuern statt über max-width (das Problem sind ja niedrige viewports, nicht schmale).
