### ISSUE TITLE
Refactor Reports: Split rather large components up into subcomponents

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.platform#20]
Refactoring in mehrere module

- [x] Reports/pages/OverviewMap/components/ReportDetails.js
- [x] Reports/pages/OverviewMap/components/ReportMarkersClustered.js
- [ ] Reports/pages/SubmitReport/components/LocateMeMap/index.js
- [ ] Reports/pages/SubmitReport/components/UploadPhotoInput.js
- [x] Reports/pages/SubmitReport/pages/ReportSubmitted.js

Und durch refactoring kürzen könnte man

- [ ] Reports/pages/SubmitReport/SubmitReportDialog.js

**Comment by ciex** [comment]
Auftrennen in mehrere Module würde ich

Reports/pages/OverviewMap/components/ReportDetails.js
Reports/pages/OverviewMap/components/ReportMarkersClustered.js
Reports/pages/SubmitReport/components/LocateMeMap/index.js
Reports/pages/SubmitReport/components/UploadPhotoInput.js
Reports/pages/SubmitReport/pages/ReportSubmitted.js

Und durch refactoring kürzen könnte man

Reports/pages/SubmitReport/SubmitReportDialog.js

ReportsState würde ich hier jetzt mal rausnehmen. Fehlt hier noch etwas offensichtliches? @geomC
