### ISSUE TITLE
Die nutzerspezifischen Fragen werden falsch ausgewählt

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.platform#201]
Als Fußgänger oder Autofahrer bekomme ich die Frage motivationalfactors: https://zpl.io/VKQ7mOR 
Ich sollte stattdessen bekommen bikeReasons: https://zpl.io/V49GZo0

Als Fahrradfahrer / pot. Fahrradfahrer sollte ich auch die Frage bekommen bicycleUse: https://zpl.io/VK6JvRA

**Comment by ciex** [comment]
> Bei mir taucht dir Frage auf, wenn ich Radfahrer bin, aber nicht, wenn ich pot. Radfahrer bin, dort soll sie auch auftauchen

> ALs Autofahrer und Fußgänger bekomme ich immer noch die falsche Frage.
