### ISSUE TITLE
Refactor Reports: De-Duplication

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.platform#21]
Re-use existing components.

Things like 

- buttons
- typography elements (headings etc.)
- wrappers used for positing

have been duplicated while developing views under time pressure. I already de-duplicated code, but there is still work to do.

A focus should be what features defined in "the other part" of the application (plannings and hbi) can be re-used, I did not find much time to check the existing code.

**Comment by ciex** [comment]
Superseded by https://github.com/FixMyBerlin/fixmy.platform/issues/257
