### ISSUE TITLE
Bilder manchmal zu ähnlich

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#215]
Die Bilder manchmal zu ähnlich. Wir haben das Feedback bekommen, dass der Wechsel zu einer neuen Szene dadurch nicht deutlich genug ist. Deshalb soll zwischen den Szenen auf dem Bild ein kleines Loader-Icon erscheinen und das Bild am besten kurz abgedunkelt werden. (Oder alternativ ein anderer Effekt)

**Comment by ciex** [comment]
Zwischen den Szenen wird jetzt das Lade-Bild gezeigt.
