### ISSUE TITLE
Konto lässt sich nicht verifizieren

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#217]
Das Konto lässt sich nicht verifizieren. 
URL: /bestaetigen/Mjk5/5bt-5872009431ad880a03e4?newsletter=yes

Problem ist, dass beim erfolgreichen aktivieren über /api/users/confirm/ nichts vom Backend als Antwort zurückgegeben wird, weshalb ein Fehler geworfen wird.

**Comment by ciex** [comment]
Das Problem sollte hiermit gelöst sein.

https://github.com/FixMyBerlin/fixmy.frontend/pull/265
