### ISSUE TITLE
Refactor Reports:  Cleanup ReportState

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.platform#22]
- [ ] restucture state object, use subreducers
  - [ ] reflect API report entity structure in local state, get rid of marshalling logic
  - [ ] unify syntax for action creators, follow [flux-standard-action](https://github.com/redux-utilities/flux-standard-action) as it is done already
I'll stick to the existing architecture of keeping all types, actions and the reducer in one file (i guess this comes frome [ducks-modular-redux](https://github.com/erikras/ducks-modular-redux)). Within the reducer tests we will use action creators instead of actions, which is a good aproach ([see this medium article](https://dev.to/ph1/a-nice-way-to-test-redux-reducers-and-actions-2npe))
  - [ ] use immutability helper like [seamless-immutable](https://www.npmjs.com/package/redux-seamless-immutable)
  - [ ] When already at it, maybe add tests already, [resource regarding redux tests](https://medium.com/javascript-scene/10-tips-for-better-redux-architecture-69250425af44)
- [ ] Once we have test converage, reduce boilerplate using https://github.com/viniciusdacal/redux-arc

**Comment by geomC** [comment]
Komme mit dem Zerlegen der Reducer und dem Schreiben von Tests gut voran. 
![image](https://user-images.githubusercontent.com/12786207/65378746-669cea00-dcbd-11e9-87cd-1aee30da8c44.png)

**Comment by ciex** [comment]
Ich schließe das Ticket für's erste. Einige Sachen wurden verbessert, vielleicht nicht alles, aber das sollten wir dann wieder aufnehmen, wenn wir mit der Umfrage bzw. dieser Codebase weitermachen.
