### ISSUE TITLE
Seitenlayout im Internet Explorer

### ISSUE THREAD

**Issue by d-m-** [FixMyBerlin/fixmy.platform#220]
* Die Höhe des Content-Containers passt sich im Internet Explorer dem Content an, zum Teil führt das zu Layoutproblemen (sharing buttons)
* Auf den Slides mit den Rendering ist er jedoch wesentlich höher, sodass es unten auf der Seite einen weißen Bereich gibt
* Zusätzlich erscheint im IE der Fortschrittsbalken ("X von Y Bewertungen") nicht

![IE3](https://user-images.githubusercontent.com/8940346/69868269-8c400400-12a9-11ea-8397-5255009f8171.png)
![IE2](https://user-images.githubusercontent.com/8940346/69868270-8c400400-12a9-11ea-90e3-fe57f3922998.png)
![IE1](https://user-images.githubusercontent.com/8940346/69868271-8c400400-12a9-11ea-8cec-555095725103.png)

**Comment by chrtze** [comment]
Welche IE Version wurde hier verwendet?

**Comment by chrtze** [comment]
![Screenshot 2019-12-05 at 15 52 52](https://user-images.githubusercontent.com/3797215/70246471-1ab7f800-1778-11ea-8dc9-80611bf0be3c.png)

Ein möglicher fix ist hier eingebaut: https://github.com/FixMyBerlin/fixmy.frontend/pull/276
