### ISSUE TITLE
ZipInput: Eingabe von mehr als 5 Ziffern möglich

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.platform#222]
Ist mir beim e2e Testen aufgefallen.
Es wird [empfohlen ](https://uxplanet.org/address-field-design-best-practices-a80390caaee0) das Eingabefeld dann auch in der Breite auf die zu erwartende Zeichenkettenweite zu begrenzen.

**Comment by geomC** [comment]
Habe es versucht schnell selbst per PR zu fixen. Sehe aber gerade, dass das Begrenzen nicht so einfach ist (`maxLength` kann nicht benutzt werden). https://stackoverflow.com/questions/8354975/how-can-i-limit-possible-inputs-in-a-html5-number-element

Lasse das mal offen.

**Comment by ciex** [comment]
Entsprechend deinem Link könnte man das ja durch `max=99999` lösen. Allerdings kann man ja auch nicht auf weiter klicken, wenn man eine längere Postleitzahl eingegeben hat und ich bin mir sicher, dass niemand das Problem hätte, in der Situation nicht zu verstehen, dass die (eigene) Postleitzahl nicht stimmt, die man da eingegeben hat.

**Comment by d-m-** [comment]
Nicht getestet, aber sowas wie <input inputmode="numeric" pattern="\d{5}" type="text"> könnte gehen und Ziffernblock auf mobile anzeigen.
