### ISSUE TITLE
Anzahl bewerteter Situationen wird falsch gezählt

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#223]
Und zwar wenn man in der Umfrage eine Seite zurück geht und die Situation noch mal (neu) bewertet.
Wenn ich die selbe Situation durch zurück gehen mehrfach bewerte, wird der Zähler immer weiter hochgezählt, jedoch wird die Bewertung ja letztlich nur einmal gespeichert.

![grafik](https://user-images.githubusercontent.com/474596/69944328-42dcf800-14e7-11ea-9e9e-2e2cd3f8852d.png)

**Comment by ciex** [comment]
Was genau passiert wenn man zurückgeht und nochmal bewertet?

**Comment by ciex** [comment]
Kann ich das schließen oder besteht dieser Fehler noch? @hekele

**Comment by ciex** [comment]
In Absprache mit Boris behebe ich diesen Bug nicht, da ich nicht glaube, dass das je einem User auffallen würde und markieren die entsprechende Stelle aber im Code, so dass dies bei zukünftiger Weiterentwicklung des Tools sichtbar bleibt.
