### ISSUE TITLE
Sicherstellen, dass Test-Suite bei verschiedenen Städte-Konfigurationen läuft

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#263]
# Problembeschreibung

* src/config/bonn/index.ts bennent nur einen Teil der Routen, die die Berlin Config spezifiziert
* src/routes.js (Das Zentrale File, dass in der Config gefundene Routen auf Components mappt) sorgt dafür, dass bestimmte pages/components nicht gerendert werden:
  * `katasterKI`
  * `projects`, `status`, `analysis`

Dieses Pattern skaliert eventuell, d.h. es können weitere Routenkonfigurationen folgen, die durch die darin vorgenommenen Änderungen Teile der App nicht verfügbar machen.

Es gilt Cypress so so konfigurieren, dass je nach der in der `.env` definerten `REGION` nur e2e Tests gestartet werden, die Bereiche der App betreffen, die nicht geladen werden.

# Lösungsansätze

## Ansatz 1: Gruppieren der Testfiles in Unterordnern

* Cypress Tests wieder zentral im Cpyress Ordner halten
* Guppieren (generisch, Städtespezifisch) durch Ablage in entsprechenden Unterordnern, s. https://stackoverflow.com/questions/50993299/easy-way-of-running-different-groups-of-cypress-tests

![image](https://user-images.githubusercontent.com/12786207/76708165-0ed3be80-66f5-11ea-9b83-c2a241a1342a.png)

+ Strukturierung durch Ordnerstruktur statt Listen von Dateinamen
- Testfiles müssen gedoppelt werden. **Löst das Problem nicht**

## Ansatz 2: RegEx Pattern:

* Wie beim Ansatz 1 funktioniert dies nicht gut, da ein Testfile für mehrere Städtekonfigurationen laufen muss. Ich kann also nicht nur eine einzige Markierung (Verwenden des Regionsnamen im Dateinamen) anbringen

## Ansatz 3:

* [Tests mit Conditionals überspringen](https://stackoverflow.com/a/56298024)

* Prüfen

### Wie kann das grundsätzlich umgesetzt werden?

1. `REGION` vor oder zu Beginn der Cypress Tests auslesen

2. Je nach Wert für `REGION` Liste (nicht) der zu durchlaufenden Tests kompilieren bzw. auswählen.
   Dazu gibt es mehrere Optionen:
A) Das Cypress Config Objekt in einem JavaScript File dynamisch aufbauen lassen.
   Geht nicht out-of-the-box. Dazu bräuchte es statt einer `cypress.json` eine `cypress.js`. Dafür gibt es
   zumindest ein Proposal: https://github.com/cypress-io/cypress/issues/5218,
   die Umsetzung ist aber noch offen.
B) Unterschiedliche Aufrufe für Cypress Tests schaffen, welche auf die jeweils passende ´Cypress.json´ zeigen
`-` Dopplung von Konfigurationsparametern in den JSONs
`-` Aufgeblähte `package.json` scripts
C) [CLI Overrides](https://docs.cypress.io/guides/references/configuration.html#Overriding-Options) verwenden.
   
  Wäre IMHO – zusammen mit der Nutzung von [nps](https://www.npmjs.com/package/nps) die beste Lösung.
 Im nps Script würde die Städtekonfiguration per `dotenv` rausgelesen werden und die Liste der (nicht) auszuführenden Tests zusammengestellt werden.

### UPDATE

Am einfachsten scheint sich das Vorhaben im [Plugins File](https://docs.cypress.io/api/plugins/configuration-api.html#Usage) umsetzen zu lassen.

BTW: `Cypress.config()` kann nicht genutzt werden, da die Konfiguration von Cypress nur von innerhalb eines TestFiles geändert werden kann. https://docs.cypress.io/api/cypress-api/config.html#Syntax

#### A: Blacklisting 

`+` Für den aktuellen Anwendungsfall (für bestimmte Städtekonfigurationen bestimmte Features *nicht* testen) wahrscheinlich am intuitivsten
`-` Funktioniert nur so lange, wie neue Städte-Konfigurationen keine eigenen Features mit sich bringen, die anderen Bereichen nicht zur Verfügung stehen

[`ignoreTestFiles`](https://docs.cypress.io/guides/references/configuration.html#Folders-Files)
![image](https://user-images.githubusercontent.com/12786207/76708175-23b05200-66f5-11ea-9d81-2f68e91d0b04.png)

#### AB: Whitelisting
`-` verbos
`+` Wahrscheinlich am nachhaltigsten

[`testFiles`](https://docs.cypress.io/guides/references/configuration.html#Folders-Files)

![image](https://user-images.githubusercontent.com/12786207/76708183-29a63300-66f5-11ea-844e-dfe2ed758e06.png)

**Comment by ciex** [comment]
Städt-Konfiguration kann jetzt auf https://elegant-hugle-53926c.netlify.com/ getestet werden

**Comment by geomC** [comment]
@ciex Ich werde es erstmal relativ stupide umsetzen, so dass cypress- und jest-tests auch mit ´REGION=bonn´ aufgerufen werden können.

Wir sollten in einem zweien Schritt mal darüber diskutieren, ob wir nicht besser [nps ](https://www.npmjs.com/package/nps) und ggf. zusätzlich [nps-utils] einsetzen sollten.

Pro/Contra

**-** Aufwand zum Einlernen
**+**  wenig aufgeblähte package.json
**+**  Code-Deduplizierung durch Nutzung von Variablen, Kontrollstrukturen, Funktionen, Imports, ...
**+**  Scripts können gleichzeitig (_concurrent_) laufen

**Comment by geomC** [comment]
Mein Verständnis davon wie das funktionieren soll:

# e2e Tests 

gehen gegen eine lokal laufende App, die mit REGION=bonn als Umbebungsvariable hat.
→ Entweder start-server-and-test Umgebungsvariable mit reingeben 
ODER (wenn das nicht geht)
dev-server und tests getrennt und nacheinander aufrufen

# unit- und integration-Tests (Jest)



Entweder
* [Jest anweisen dotenv zu laden](https://medium.com/@lusbuab/using-dotenv-with-jest-7e735b34e55f)
* lokal zum testen .env file erzeugen und `REGION` setzen
* in CI [analog vorgehen](https://stackoverflow.com/a/55581164)



Interessant für den Umgang mit unterschiedlichen .envs
https://www.npmjs.com/package/dotenv-flow
--> erlaubt Kaskadierung

**Comment by geomC** [comment]
Habe gesehen, dass 
https://github.com/FixMyBerlin/fixmy.frontend/pull/332/files#diff-4bcea4966f5e62ded90298c2b0907445R1
ja schon dafür sorgt, dass Cypress die Umgebungsvariablen aufgreift.

![image](https://user-images.githubusercontent.com/12786207/76151083-25549700-60b1-11ea-8920-00fb27b1b5cc.png)

Waren hier dann vielleicht nur die Jest Tests gemeint?

Dann sollte aus meiner Sicht alles passen, stelle den PR.

**Comment by geomC** [comment]
Habe das Ticket falsch verstanden. Das Ziel:

e2e Tests nur für Features, die für eine bestimmte Städtekonfiguration getoggled sind

**Comment by geomC** [comment]
Wir können Tests logisch gruppieren mit [jest-runner-groups](https://www.npmjs.com/package/jest-runner-groups)

**Comment by geomC** [comment]
e2e Tests wenn `REGION=bonn` gesetzt ist:

![image](https://user-images.githubusercontent.com/12786207/76701354-b1257f00-66c0-11ea-96fb-ba15774eb8f8.png)

**Comment by geomC** [comment]
Closed accidently

**Comment by geomC** [comment]
Mein Ansatz:

* Cypress Tests wieder zentral im Cpyress Ordner halten
* Guppieren (generisch, Städtespezifisch) durch Ablage in entsprechenden Unterordnern, s. https://stackoverflow.com/questions/50993299/easy-way-of-running-different-groups-of-cypress-tests

**Comment by geomC** [comment]
Ich habe die Beschreibung oben nochmal aktualisiert.
