### ISSUE TITLE
Möglichkeit zum Upload von Radbügeln für neuen Meldedialog

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#264]
- [ ] KML- oder KMZ-Dateien mit Ortsangaben sollen als Meldungen in die Datenbank importiert werden können
- [ ] Dabei sollen die Namen entfernt werden

**Comment by geomC** [comment]
Habe das Geokoordinaten angereichertes KML im Slack gepostet.
Code: https://github.com/geomC/fixmykml
