### ISSUE TITLE
Slider akzeptiert nur ungerade Zahlen in IOS13

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.platform#28]
Bugmeldung von einem User:
"In Safari und IOS13 (Release morgen) kann man keine gerade Anzahl Bügel bestellen. Es springt immer auf die ungeraden Ziffern."

**Comment by geomC** [comment]
Versuche es heute Abend mit Browserling. Wenn ich damit nicht weiterkomme, muss ich das Ticket abgeben, da ich kein iPhone + Mac zwecks debugging verfügbar habe.

**Comment by geomC** [comment]
Browserling bietet kein iOS. Habe noch [smartbear]() versucht, das noch kein ios 13 bietet und wenn dann wahrscheinlich auch nicht im Rahmen von einem free trial. https://app.crossbrowsertesting.com

**Comment by geomC** [comment]
Komme hier also nicht weiter.

**Comment by geomC** [comment]
@chrtze Kann das Issue geschlossen werden?
