### ISSUE TITLE
Als Datenredakteurin kann ich Abschnitte in QGis pflegen

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#3]
- Abschnitte werden als Shape File zusammen mit Attributen importiert.
- Geometrien werden direkt in den Abschnitten gespeichert, Kanten fallen weg.
- Kanten-Datensatz muss nicht mehr importiert werden.
- Kanten-Datensatz soll gelöscht werden.
- Anleitung (Workflow) für Datenredaktion schreiben.

Attribute für das Shape-File:
- id
- street_name
- suffix
- street_category
- borough

**Comment by ciex** [comment]
Es wurde hier keine Anleitung geschrieben wie in der Anforderung spezifiziert.
