### ISSUE TITLE
LocatorControl uses js alert and has broken state when user disallows location acccess

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#34]
The component's behavior should be improved when users disallow location access. Right now, an alert box is displayed and the loading state is not reset. Instead, an error message should be displayed as part of the UI and the loading state should reset.

https://github.com/FixMyBerlin/fixmy.frontend/blob/278fefcce9eec9f821641d218030e504c9a3f88d/src/pages/Map/components/LocatorControl.js#L63-L66

**Comment by geomC** [comment]
I looked into this, I see two solution aproaches:

1. Connect component with store, add `error` property to `AppState`. If we do this, we should do a greater refactoring which should be integrated in other tasks touching this, e.g. #57:
* display `ErrorMessage` at top Level, see #23
* where we can keep a function to resolve the dispatched error (at least to unset the error message) when the user clicks an okay / retry button in the ErrorBessage. see https://redux.js.org/faq/organizing-state/#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state

**Pro**: Unify look and feel, de-duplicate logic
**Contra**: effortful 

2. Add a custom `ErrorMessage` component that opens next to the Locator.
**Pro**: Might look nice if its small, unintrusive and next to the button
**Contra**: We only postpone the refactoring I described above

@ciex What do you think?

**Comment by geomC** [comment]
Update on this:

I think for now it is fine to keep the error within the component state and invoke the `ErrorMessage` component. I implemented this, see https://github.com/FixMyBerlin/fixmy.frontend/commit/aa8b85eb0b8e506d268a8533640dee2bc80f071e.
This would only lead to problems if other components higher up in the componentTree (Reports/OverviewMap or Map) would also display an instance at the same time, which is rather unlikely.

Now there is the question how to react to the denial:
If the user has denied the request, the browser persists that information. 
There seems to be no way arround that, https://stackoverflow.com/q/20678707
So every new tap on the button leads to the same error message.

![fixmy_geolocation denial](https://user-images.githubusercontent.com/12786207/73395688-4d95ec80-42e0-11ea-8b4f-c714cb7ad286.gif)

What we could do is to disable the control or to hide once after the errorDialog has been dismissed.

**Comment by geomC** [comment]
> What we could do is to disable the control or to hide once after the errorDialog has been dismissed.

That is what I did: https://github.com/FixMyBerlin/fixmy.frontend/commit/f4e71fc77e5be7225325221da305e612f0103993
