### ISSUE TITLE
Error uploading mapbox tilesets from project data export

### ISSUE THREAD

**Issue by norabi** [FixMyBerlin/fixmy.platform#342]
#### Issue description
Beim Übertragen der Geometrien von Django nach Mapbox mit dem Befehl
python manage.py uploadtileset /tmp/projects_export.json --dataset projects
bekomme ich eine Fehlermeldung.
![fehler](https://user-images.githubusercontent.com/52205086/80910082-6f629d80-8d2d-11ea-9430-d229b3bd7853.PNG)

(der Export python manage.py exportprojects /tmp/projects_export.json funktioniert noch)

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

#### Additional details / screenshot

- ![Screenshot]()
-

**Comment by ciex** [comment]
Couldn't replicate this today.
