### ISSUE TITLE
e2e tests for KatasterKI page fail because of undefined initial state

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#349]
#### Issue description

When running the test suite for the KatasterKI page, all tests fail because the reports page ErrorState reducer cannot be initialized. It is being initialized by reading initial state from `window.intialState`. That value however doesn't contain initial state for the reports reducers but only for the KatasterKI reducers. 

#### Steps to reproduce the issue

1.  Run e2e test suite

#### What's the expected result?

- Tests pass

#### What's the actual result?

- Tests fail

#### Additional details / screenshot

- Cypress was recently updated to version 4.x, however the error also exists when run with the version of Cypress we were using previously 

```
Uncaught Error: Reducer "ErrorState" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined. If you don't want to set a value for this reducer, you can use null instead of undefined.

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'whyBiking'
```

**Comment by s-pic** [comment]
The problem is that

**Comment by s-pic** [comment]
See https://github.com/FixMyBerlin/fixmy.frontend/pull/441
