### ISSUE TITLE
Update Spielstrassen

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.platform#360]
Die Spielstraßen APP soll aktualisiert werden:

- [ ]  Aktualisierung der Übersichtskarte, die neue Karte liegt hier https://drive.google.com/file/d/1cEMRj-rT5F3LZtvSCaIaO6dATDM0xB6-/view 
- [ ] Aktualisierung der Kartenausschnitte zu folgenden Straßen: Die Karten ausschnitte finden sich hier: https://drive.google.com/drive/folders/1lXOy6G7ydBi7BA6764fGvBfrlPxeoXM9
- Arndtstraße
- Südstern 
- Lausitzer Platz
- Bänschstraße
- Waldemarstraße
- Krossener Straße
- [ ] Die bisherige Lilienthalstraße sol jetzt Südstern heißen (geänderter Abschnitt)

**Comment by ciex** [comment]
Diese Änderungen sind obsolet.
