### ISSUE TITLE
Mapbox doesn't support CRS member in GeoJSON-uploads

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#388]
#### Issue description

As described here https://macwright.org/2015/03/23/geojson-second-bite#projections

This is a feature request to remove crs from all GeoJSON exports.

**Comment by s-pic** [comment]
Can I help here in any way?

**Comment by ciex** [comment]
@s-pic sorry I didn't reply. It was mostly a reminder for me. Would you like to get into working with Python?

**Comment by s-pic** [comment]
Sure!
