### ISSUE TITLE
Layout-Updates Forschungsseite

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.platform#389]
- [x] Alle Icons im FeelsafeIndex, sollten die gleiche Strichstärke und Schwärzung haben nach Vorbild des Autoicons.

- [x] Spacing unter Überschriften verringern, damit der Zusammenhang mit dem Text klar ist.  s. Layout https://zpl.io/bPJ8gdL

- [x] Die Zusammenfassung sollte als eigenes Kapitel im Inhaltsverzeichnis erscheinen mit der möglichkeit direkt dort hin zu springen.

- [x] Wenn die Werte in den Barcharts nicht mehr gut angezeigt werden können, sollte dort ein Sternchen (o.ä.) angezeigt werden und der Wert im Tooltip angezeigt werden. GGf. auch alle Werte ohne Nachkommastellen anzeigen und den Wert mit den zwei Nachkommastellen nur im Tooltip anzeigen.
<img width="284" alt="Screenshot 2020-07-07 15 41 12" src="https://user-images.githubusercontent.com/39826825/86790084-4c73a300-c068-11ea-8871-8403a8bf9166.png">

**Comment by ciex** [comment]
Zu 4: Der Wert im Tooltip wird dann nur bei Hover angezeigt
