### ISSUE TITLE
Cypress deprecated before:browser:launch event call signature

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#404]
Running `npm run cypress open` on `develop` displays the warning

> Deprecation Warning: The before:browser:launch plugin event changed its signature in version 4.0.0

>The before:browser:launch plugin event switched from yielding the second argument as an array of browser arguments to an options object with an args property.

> We've detected that your code is still using the previous, deprecated interface signature.

> This code will not work in a future version of Cypress. Please see the upgrade guide: https://on.cypress.io/deprecated-before-browser-launch-args

A fix for this should update the call signature according to the warning.

@s-pic maybe you can look into this

**Comment by s-pic** [comment]
@ciex Sure thing
