### ISSUE TITLE
chore: adapt eslint to not care about no-use-before-define

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.platform#407]
**What's the problem you want solved?**
In various places, function are declared below the place where they are called by making use of [hoisted function declarations](https://dmitripavlutin.com/javascript-hoisting-in-details/#5-function-declarations).
```js
doSth();
function doSth() {
  // do something else
}
```
This is inetentionally done: When I read a file, I want to see the important stuff in its top section and then go down to see into certain implementation details. It is a pretty standard aproach.

Our eslint config does not allow to do so, so we have quite a couple of file- or line-based ignore rules.

**Is there a solution you'd like to recommend?**

I would like to
* adapt our eslint config to not complain about that case by adding `{ "functions": false }` to the config of `no-use-before-define`, see https://eslint.org/docs/rules/no-use-before-define
* globally remove ignore statements

**Comment by s-pic** [comment]
@ciex Is that fine for you?

**Comment by ciex** [comment]
Sorry, i agree with the rule here. However, I would also like to globally remove exceptions unless there is a good specific reason for any of them.
