### ISSUE TITLE
[Frontend] cannot run unit tests

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.platform#425]
#### Issue description

Running `npm run test` leads to the following unexpected output:
```
> cross-env NODE_ICU_DATA=node_modules/full-icu jest --verbose --config=jest/jest
.config.js

node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)
npm ERR! Test failed.  See above for more details.

Process finished with exit code 1
```

Passing `NODE_ICU_DATA` was added in https://github.com/FixMyBerlin/fixmy.frontend/commit/3884c975b2dfde32f14fa1ec3d5bb16fa533ee9e.

#### Proposed solution

I will do some research what the param means an try to fix this myself.

#### Aditional info

Sysinfo (generated with `npx -p @storybook/cli sb init`)
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.19041.423.0)
```

**Comment by s-pic** [comment]
Fixed after updating 
* my node version to the current LTS
* running `npm i -g npm`

@ciex What do you think: Should we prevent problems related to outdated node versions by specifiying the minimum node version [like so](https://stackoverflow.com/a/50798589/5418403)?

**Comment by ciex** [comment]
That error was because I added the `full-icu` package since the last time you ran `npm install`. 

In `.nvmrc` we specify the exact node version to use. However, this only works if you use `nvm`. Let me look into the behavior of that `package.json` field you suggested and get back to this.

**Comment by cafca** [comment]
Yes it looks good. Can you make a PR? Node version should be `>=` whats in the `.nvmrc` then, right? Or do you think we should move to a newer node version as well? I'm not up to date what the advantages of that could be.

**Comment by s-pic** [comment]
Do you see a reason why we should support a Node Version older than the current LTS (12.18.3)?

**Comment by cafca** [comment]
@s-pic actually, no.
