### ISSUE TITLE
Config selects production backend by default

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.platform#426]
#### Issue description
When running tests that trigger requests to the backend, I want to make sure that the productive database is not touched. IMHO we should use the _staging_ backend by default and  **use the production backend only in the CI**.

From what I remember we used to pass `cross-env CONFIG_ENV=dev` as param to jest.
Now we don't. I think that is dangerous.

#### Proposed solution

Minimum Solution: Revert logic in `src/config/default/base.ts` to assume staging backend by default.
Maximum Solution: I still favor an `env.ts` to 
* parse .env files using dotenv once
* read other env vars passed by ci once
* assign default values
* compute derived flags
* gain intellisense

##### Additional info

Sys info (generated running `npx -p @storybook/cli sb info`)
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.19041.423.0)
```

**Comment by s-pic** [comment]
Actually it should be sufficient to prepend the jest call in the npm `test` script with `BACKEND=staging`, I will create a PR.

**Comment by ciex** [comment]
I agree that it's a good idea to default to the staging backend. However, I will have to check that all production build jobs set `BACKEND=production` before making this change. I will assign this ticket to me for that.
