### ISSUE TITLE
CTA on reports overview map doesn't handle clicks until data is fully loaded

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.platform#429]
#### Steps to reproduce the issue

1.  Visit https://radbuegel-aachen.de/meldungen/karte
2. Click "mehr Infos" before data has finished loading

#### What's the expected result?

- Redirect to landing page

#### What's the actual result?

- Nothing happens

**Comment by cafca** [comment]
@s-pic would you mind looking into this?

**Comment by s-pic** [comment]
Sure

**Comment by s-pic** [comment]
https://github.com/FixMyBerlin/fixmy.frontend/pull/530 should do it.

My bad, did not have this case in mind.

Wonder if we should add e2e tests for the case that the loading takes some time.
