### ISSUE TITLE
Meldungs-Details: Share Button nicht dargestellt /falsche Darstellung Button

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.platform#44]
![image](https://user-images.githubusercontent.com/12786207/64284850-c45dd200-cf5a-11e9-9132-59fa8900774f.png)

Der Button zum Teilen einer Meldung in der Detailansicht soll entsprechend des Layouts https://zpl.io/VOm6RZj dargestellt werden.

**Comment by ciex** [comment]
Kann ich dieses Ticket schließen?
