### ISSUE TITLE
Landing page for Reports in Fhain Xberg shows content about aachen

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.platform#448]
Not a 100% sure here if its a real bug but I felt like it was.

#### Issue description

See the title

#### Steps to reproduce the issue

Visit https://fixmyberlin.de/meldungen/radbuegel/friedrichshain-kreuzberg/landing

#### What's the expected result?

I only see visual items regarding reports in fhain xbgerg.

#### What's the actual result?

- I see Logos from Aachen

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/12786207/93717468-59d40000-fb76-11ea-89fa-257ce3352993.png)

**Comment by cafca** [comment]
@s-pic not really a bug. We never updated that landing page after closing report submission.
