### ISSUE TITLE
Bugs / Testing zu #58

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.platform#45]
Bugs und kleiner Detailanpassungen nach Testing von issue FixMyBerlin/fixmy.frontend#58

- [x] Das Fadenkreuz bei der Positionsbestimmung sollte größer und breiter. (vgl. https://zpl.io/agPeBZO) <img width="358" alt="Screenshot 2019-09-04 15 44 14" src="https://user-images.githubusercontent.com/39826825/64260502-4504da00-cf2b-11e9-9e40-63d12e83d034.png"> 

- [x] Der Button 'Position bestätigen' sollte ca. 5% höher positioniert werden. (Wird sonst bei vielen mobilen Browsern verdeckt.)

- [ ] Der Zeilenabstand des Fliesstexts sollte überall gleich sein. (Abweichungen sind mit aufgefallen bei den Hinweistexten bei https://zpl.io/amyNn1K und https://zpl.io/amdM30A). <img width="330" alt="Screenshot 2019-09-04 15 49 11" src="https://user-images.githubusercontent.com/39826825/64260659-90b78380-cf2b-11e9-8b59-b52e0a571cf8.png">

**[Sascha]: Beide Beispiele verwenden die selbe Typographische Komponente, die den Standard Zeilenabstand eines HTML Paragraphs hat. Sehe hier keinen Handlungsbefarf**

- [ ] Die Höhe des Emaileingabefeldes sollte größer sein (vgl. https://zpl.io/a75KEzj)
<img width="328" alt="Screenshot 2019-09-04 15 50 29" src="https://user-images.githubusercontent.com/39826825/64260744-bd6b9b00-cf2b-11e9-9709-d7b73f89f032.png">

**[Sascha] Hatte ich angepasst (https://github.com/FixMyBerlin/fixmy.frontend/commit/7735dee8f075685e0418e680f823ea177c532f4a), habe aber nicht gesehen, dass [der Merge von reports-userhandling nach feedback-ba](https://github.com/FixMyBerlin/fixmy.frontend/commit/14d6ac4a6d39bdc9be4480d7c46bc4dbd8230050)** das wieder überschrieben hat. Ist jetzt auf die Schnelle für mich nicht fixbar, da es sich um generische, teilweise gekapselte (Formik) Logik handelt. Müsste in ein extra Ticket überführt werden, vielleicht kann sich das @moklick nochmal anschauen.

- [x] In der Detailansicht wird noch kein Pin zur Darstellung des Status angezeigt (Farbe zunächst gelb)

**Comment by ciex** [comment]
Kann ich dieses Ticket schließen?
