### ISSUE TITLE
Registrierung / Login

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#47]
Wenn ein User nach dem Dialog die Danke-Seite erreicht hat, dann soll er die Möglichkeit haben, sich zu registrieren. In diesem Fall soll die Meldung mit dem neu erstellten Account verknüpft werden. Besitzt der User bereits einen Account, dann soll die Meldung mit dem bereits existenten verknüpft werden. 

Layout, Danke-Seite: https://app.zeplin.io/project/5ad5f75adf221b9343d45559/screen/5c0fb7795ff9082436cffc5d
Layout, Fehlermeldung: https://app.zeplin.io/project/5ad5f75adf221b9343d45559/screen/5d5429b18d5c26520b8184e3
Layout, Warte auf Bestätigung: https://app.zeplin.io/project/5ad5f75adf221b9343d45559/screen/5d54260d0d6e049b182aa3b9

Prozess: https://drive.google.com/file/d/14Asbf1mn34Cno5gkDShgOlDJAc42LXyU/view

Endpoint: http://api.fixmyberlin.de/api/users/create
Daten: [user: email, newsletter: 0|1, data: [type: report, id: 123]]

**Gewünschtes Verhalten**

*1. E-Mail-Adresse zu bestehendem Login & bestehendem Newsletter eingegeben, ...*

...außerdem Checkbox Login erstellen & Newsletter angeklickt:
- [x] Nachricht erscheint: "Du hast bereits einen Login, bitte [Link:melde Dich an]." 

...außerdem nur Checkbox Login erstellen angeklickt:
- [x] Nachricht erscheint: "Du hast bereits einen Login, bitte [Link:melde Dich an]." 

*2. E-Mail-Adresse zu bestehendem Login & ohne bestehendem Newsletter eingegeben, ...*

...außerdem Checkbox Login erstellen & Newsletter angeklickt:
- [x] Nachricht erscheint: "Du hast bereits einen Login, bitte [Link:melde Dich an]." 

...außerdem nur Checkbox Login erstellen angeklickt:
- [x] Nachricht erscheint: "Du hast bereits einen Login, bitte [Link:melde Dich an]." 

*3. E-Mail-Adresse ohne bestehendem Login & bestehendem Newsletter eingegeben, ...*

...außerdem Checkbox Login erstellen & Newsletter angeklickt:
- [x] Danke-Seite erscheint
- [x] E-Mail mit Double Opt Inn kommt an
- [x] Aktivierung des Logins
- [x] Bestätigungs-Seite erscheint
- [x] Registrierung in Newsletter bleibt bestehen
- [x] Meldung wird mit Login verknüpft

...außerdem nur Checkbox Login erstellen angeklickt:
- [x] Danke-Seite erscheint
- [x] E-Mail mit Double Opt Inn kommt an
- [x] Aktivierung des Logins
- [x] Bestätigungs-Seite erscheint
- [x] Meldung wird mit Login verknüpft
- [x] Registrierung in Newsletter bleibt bestehen

*4. E-Mail-Adresse ohne bestehendem Login & ohne bestehendem Newsletter eingegeben, ...*

...außerdem Checkbox Login erstellen & Newsletter angeklickt:
- [x] Danke-Seite erscheint
- [x] E-Mail mit Double Opt Inn kommt an
- [x] Aktivierung des Logins
- [x] Bestätigungs-Seite erscheint
- [x] Meldung wird mit Login verknüpft
- [x] Eintragen in Newsletter funktioniert (nach Verifizierung des Logins)

...außerdem nur Checkbox Login erstellen angeklickt:
- [x] Danke-Seite erscheint
- [x] E-Mail mit Double Opt Inn kommt an
- [x] Aktivierung des Logins
- [x] Bestätigungs-Seite erscheint
- [x] Meldung wird mit Login verknüpft
- [x] Kein Eintragen in Newsletter

**Comment by ciex** [comment]
Kann ich dieses Ticket schließen?
