### ISSUE TITLE
Anpassungen Detail Meldung

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#48]
/meldungen/radbuegel/friedrichshain-kreuzberg/karte/8
- [x] Sharing geht nicht
- [x] Text Sharing zu klein
- [x] Liken geht nicht
- [x] Das Feld für Status sollte in jedem Fall angezeigt werden.
- [x] Unter der Adressangabe sollte nicht “Abschnitt 1” stehen dafür “Meldung XXX”
- [x] Die Karte kann in der weitesten Zoomstufe nur nach oben oder unten verschoben werden
- [x] in der Detailansicht kann die Karte gar nicht verschoben werden. (Firefox, OSX)

**Comment by ciex** [comment]
Kann ich dieses Ticket schließen?
