### ISSUE TITLE
Django NullBooleanField is deprecated

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.platform#508]
#### Issue description

The `profile` model uses a NullBooleanField, which is deprecated and will be removed in Django 4. It should be replaced by `BooleanField(null=True)`.

**Comment by BobinMathew** [comment]
Hi @cafca 
```python
has_trailer = models.NullBooleanField(_('has trailer'), blank=True, null=True)
```
is this the code you want to replace?

**Comment by BobinMathew** [comment]
Do you wnat to replace it like this?
Changed code ⬇
```python
has_trailer = models.BooleanField(_('has trailer'), blank=True, null=True)
```

**Comment by BobinMathew** [comment]
If you like the solution please assign this issue to me 😊

**Comment by cafca** [comment]
Hey @BobinMathew, thank you for jumping at this issue immediately. I will add a comment to your pull request.
