### ISSUE TITLE
S3 upload fails with Python 3.9

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.platform#569]
#### Issue description

Using Python 3.9 and boto3, the `EventPermitDocumentView` in `permits/views.py` fails testing.

**Comment by ohrie** [comment]
After upgrading some dependencies, this doesn't fail anymore: https://github.com/FixMyBerlin/fixmy.platform/commit/a06c8b08e64b49b5a262a0ede074f2736edb2701
