### ISSUE TITLE
Alle Planungs-Linestrings sind pink

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#64]
-> https://release--fixmyberlin-staging.netlify.com/planungen
Richtig wäre eine Unterscheidung nach Status.

**Comment by ciex** [comment]
Fixed by https://github.com/FixMyBerlin/fixmy.frontend/commit/cdce8a77ca1e0fee44b340281d598ea57f1b3118 and https://github.com/FixMyBerlin/fixmy.frontend/commit/47b67a085dffb633010f755ae155617d5ea9df77
