### ISSUE TITLE
Permalinks auf Planungen funktionieren nicht mehr

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#67]
-> https://release--fixmyberlin-staging.netlify.com/planungen/80/
Vorher war die URL /planungen/9028/friedelstrasse
Es fehlt also der Straßenname und die ID hat sich geändert. Die URL sollte so wie vorher "/planungen/9028/friedelstrasse" sein.
Nachtrag: Der Straßenname fehlt nur beim Klick auf den Linestring. Beim Marker wird sie gesetzt.

**Comment by ciex** [comment]
Ein Fix sollte meiner Meinung nach

Entweder

- von den alten URLs auf die neuen weiterleiten
- einen HTTP 301 response code senden

oder

- das alte URL-Schema für Planungen wieder einführen

Außerdem sollten

- eine URL des vorigen Schemas in das Release-Testing-Protokoll aufgenommen werden um auch in Zukunft die Beständigkeit von Links sicherzustellen
- eine eindeutigere Fehlermeldung im Frontend gezeigt werden, wenn man auf eine URL zu einer nicht (mehr) existierenden Planung navigiert. Derzeit wird hier nur "Ein Fehler ist aufgetreten." angezeigt.

**Comment by ciex** [comment]
Der slug ist wieder in den URLs mit https://github.com/FixMyBerlin/fixmy.frontend/pull/175

**Comment by ciex** [comment]
Zum testen: https://fixmyberlin.de/planungen/9028/friedelstrasse
