### ISSUE TITLE
Das Backend soll unter der Hauptdomain erreichbar sein

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#7]
- api.fixmyberlin.de soll abgeschaltet werden.
- API soll unter https://fixmyberlin.de/api erreichbar sein.

Einzurichtende Header für den Proxy:

`headers = {X-Forwarded-Host = "<front-end-domain>", X-Forwarded-Proto = "https"}`

**Comment by ciex** [comment]
Wann bearbeiten wir das?
