### ISSUE TITLE
Länge der Planungen unter Analyse weicht zu stark ab

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#78]
Wert zu gering (https://release--fixmyberlin-staging.netlify.com/analyse/planungen):
![grafik](https://user-images.githubusercontent.com/474596/67045336-5cd89c00-f12e-11e9-810f-219398241632.png)

Wert korrekt (https://fixmyberlin.de/analyse/planungen)
![grafik](https://user-images.githubusercontent.com/474596/67045319-5518f780-f12e-11e9-95d3-17593a9961c8.png)

Hintergrund: Die Länge der Planungen wurde bisher direkt als Wert in die DB eingespielt (in die Planning Details). Mit der Umstellung wird die Länge anhand der Geometrien der eingespielten Projekte vom Backend errechnet.

**Comment by ciex** [comment]
Länge wird jetzt aus Datenbank entnommen. Kann geschlossen werden. Im Staging stimmen die Längen nicht, da die Projektdatenbank nur im Live-System die manuell eingetragenen Längen enthält.
