### ISSUE TITLE
Performance der Projekte und Meldungen verbessern

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#88]
- /api/projects cachebar machen (Informationen ob User gelikt hat raus)
- /api/projects/ID ungecacht (Like Informationen bleiben drin)
- /api/user/likes für Loginbereich ungecacht (Daten: ID, Typ, Like)

Gleiches Verhalten für /api/reports

**Comment by ciex** [comment]
Closed by https://github.com/FixMyBerlin/fixmy.platform/pull/320
